language: php

php:
  - 5.3
  - 5.4

before_install:
  - cd ../
  - git clone git://github.com/UnionOfRAD/framework.git
  - mv li3_newrelic/ framework/app/libraries/li3_newrelic
  - cd framework
  - git submodule update --init --recursive && cd libraries/lithium
  - git fetch origin && git checkout dev && git pull --rebase origin dev && cd ../../
  - git clone --branch=master git://github.com/UnionOfRAD/li3_quality.git app/libraries/li3_quality
  - sed '$d' app/config/bootstrap/libraries.php > app/config/bootstrap/libraries.php.bak
  - mv app/config/bootstrap/libraries.php.bak app/config/bootstrap/libraries.php
  - echo "Libraries::add('li3_quality');" >> app/config/bootstrap/libraries.php
  - echo "Libraries::add('li3_newrelic');" >> app/config/bootstrap/libraries.php
  - cd app

script: ../libraries/lithium/console/li3 test libraries/li3_newrelic/tests && ../libraries/lithium/console/li3 quality syntax --library=li3_newrelic